In [3]:
import sys
sys.path.insert(1, "..")

In [5]:
from parse_game import ParseGame

In [10]:
parser = ParseGame()
parser.attach_filepath("../ESP1/738459-Spain-LaLiga-2013-2014-Celta-Vigo-Espanyol.json")

In [11]:
parser.import_game()

In [12]:
parser.extract_referee()
parser.referee_data

  MatchId RefereeId                     RefereeName
0  738459      1607  José Antonio Teixeira Vitienes

In [13]:
parser.extract_player_game()
parser.player_game_data

,MatchId,PlayerId,ShirtNo,PlayerName,Position,Started,SubOutPlayerId,SubInMinute,SubInHalf,Height,Weight,Age,ManOfMatch,Field
0,738459,83117,13,Yoel Rodríguez,GK,True,None,None,None,186,78,31,False,home
0,738459,79929,2,Hugo Mallo,DR,True,None,None,None,173,69,28,False,home
0,738459,15544,22,Gustavo Cabral,DC,True,None,None,None,182,80,33,False,home
0,738459,74938,3,Andreu Fontàs,DC,True,None,None,None,185,89,29,False,home
0,738459,105912,20,Toni Dovale,DL,True,None,None,None,173,70,29,False,home
0,738459,10623,23,Michael Krohn-Dehli,MC,True,None,None,None,171,70,36,True,home
0,738459,18219,4,Borja Oubiña,MC,True,None,None,None,179,75,37,False,home
0,738459,87080,8,Álex López,MC,True,None,None,None,177,71,31,False,home
0,738459,25956,24,Augusto Fernández,FWR,True,None,None,None,177,73,33,False,home
0,738459,102157,11,Charles,FW,True,None,None,None,179,76,35,False,home
0,738459,91267,10,Nolito,FWL,True,None,None,None,175,65,32,False,home
0,738459,106590,12,Rafinha,Sub,False,91267,65,SecondHalf,174,71,26,False,home
0,738459,108220,28,Lévy Madinda,Sub,False,87080,91,SecondHalf,182,77,27,False,home
0,738459,32227,18,David Rodríguez,Sub,False,102157,86,SecondHalf,178,75,33,False,home
0,738459,25714,14,Fabián Orellana,Sub,True,None,None,None,170,64,33,False,home
0,738459,135404,30,David Costas,Sub,True,None,None,None,184,71,24,False,home
0,738459,31923,16,Carlos Bellvis,Sub,True,None,None,None,170,65,34,False,home
0,738459,97559,1,Sergio Álvarez,Sub,True,None,None,None,180,75,33,False,home
0,738459,23154,13,Kiko Casilla,GK,True,None,None,None,190,86,32,False,away
0,738459,80957,16,Javi López,DR,True,None,None,None,180,76,33,False,away
0,738459,23633,19,Diego Colotto,DC,True,None,None,None,184,83,38,False,away
0,738459,33495,15,Héctor Moreno,DC,True,None,None,None,183,76,31,False,away
0,738459,135405,18,Fuentes,DL,True,None,None,None,177,72,29,False,away
0,738459,92691,14,David López,DMC,True,None,None,None,183,81,29,False,away
0,738459,33556,4,Víctor Sánchez,DMC,True,None,None,None,174,72,31,False,away
0,738459,24400,8,Cristhian Stuani,AMR,True,None,None,None,186,76,32,False,away
0,738459,81928,10,Pizzi,AMC,True,None,None,None,172,66,29,False,away
0,738459,1114,20,Simão,AML,True,None,None,None,170,64,39,False,away
0,738459,10060,9,Sergio García,FW,True,None,None,None,174,72,36,False,away
0,738459,99196,7,Thievy,Sub,False,81928,62,SecondHalf,180,80,27,False,away
0,738459,93212,3,Raúl Rodríguez,Sub,False,10060,81,SecondHalf,183,70,31,False,away
0,738459,71328,23,Abraham González,Sub,False,92691,74,SecondHalf,177,75,34,False,away
0,738459,105942,12,Manuel Lanzarote,Sub,True,None,None,None,178,72,35,False,away
0,738459,106595,28,Carlos Clerc,Sub,True,None,None,None,182,72,27,False,away
0,738459,122732,26,Germán Parreño,Sub,True,None,None,None,189,78,26,False,away
0,738459,1676,11,Joan Capdevila,Sub,True,None,None,None,182,78,41,False,away

In [14]:
parser.extract_game()
parser.game_data

,MatchId,League,Season,VenueName,Attendance,StartDate,StartTime,WeatherCode,HomeTeamId,HomeTeamName,...,AwayTeamId,AwayTeamName,AwayTeamManager,AwayAvgAge,HomeGoals,AwayGoals,HomeHTGoals,AwayHTGoals,HomeFTGoals,AwayFTGoals
0,738459,ESP1,2013-2014,Balaídos,21672,2013-08-19,21:00:00,5,62,Celta Vigo,...,70,Espanyol,Javier Aguirre,32.2,2,2,1,0,2,2

In [15]:
parser.extract_events()
parser.event_data

,MatchId,EventId,EventMatchId,Minute,Second,TeamId,PlayerId,StartX,StartY,Half,Type,Outcome,EndX,EndY
0,738459,1956079551,2,0,0,70,None,0,None,FirstHalf,Start,Successful,None,None
0,738459,1972265860,3,0,0,62,None,0,None,FirstHalf,Start,Successful,None,None
0,738459,1217080213,3,0,1,70,81928,50.1,48.3,FirstHalf,Pass,Successful,52.8,48.3
0,738459,100258400,4,0,2,70,10060,52.8,62.6,FirstHalf,Pass,Successful,26.1,62.6
0,738459,1916349902,5,0,3,70,33495,26.1,27.7,FirstHalf,Pass,Successful,27.2,27.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,738459,304820833,856,92,52,62,105912,20.4,100,SecondHalf,Pass,Unsuccessful,25,100
0,738459,1336410710,741,93,3,70,None,0,None,SecondHalf,End,Successful,None,None
0,738459,2022470689,858,93,3,62,None,0,None,SecondHalf,End,Successful,None,None
0,738459,1378734642,1,0,0,70,None,0,None,PreMatch,FormationSet,Successful,None,None
0,738459,589537459,1,0,0,62,None,0,None,PreMatch,FormationSet,Successful,None,None